# Generated by Django 5.1.2 on 2024-11-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cartitem_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ram',
            field=models.CharField(default='4GB', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='storage',
            field=models.CharField(default='128GB', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.URLField(default='/static/assets/default_color_image.jpg'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='ram',
            field=models.CharField(default='4GB', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='storage',
            field=models.CharField(default='128GB', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
